/*
 * AazarKhanTelstraSMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using AazarKhanTelstraSMSAPI.PCL.Controllers;
using AazarKhanTelstraSMSAPI.PCL.Http.Client;
using AazarKhanTelstraSMSAPI.PCL.Utilities;

namespace AazarKhanTelstraSMSAPI.PCL
{
    public partial class AazarKhanTelstraSMSAPIClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public AazarKhanTelstraSMSAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public AazarKhanTelstraSMSAPIClient(string oAuthAccessToken)
        {
            Configuration.OAuthAccessToken = oAuthAccessToken;
        }
        #endregion
    }
}