/*
 * AazarKhanTelstraSMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AazarKhanTelstraSMSAPI.PCL;
using AazarKhanTelstraSMSAPI.PCL.Utilities;


namespace AazarKhanTelstraSMSAPI.PCL.Models
{
    public class GetMessageStatusResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string to;
        private string receivedTimestamp;
        private string sentTimestamp;
        private string status;

        /// <summary>
        /// Where the SMS is being sent
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// When the SMS was received
        /// </summary>
        [JsonProperty("receivedTimestamp")]
        public string ReceivedTimestamp 
        { 
            get 
            {
                return this.receivedTimestamp; 
            } 
            set 
            {
                this.receivedTimestamp = value;
                onPropertyChanged("ReceivedTimestamp");
            }
        }

        /// <summary>
        /// When the SMS was sent
        /// </summary>
        [JsonProperty("sentTimestamp")]
        public string SentTimestamp 
        { 
            get 
            {
                return this.sentTimestamp; 
            } 
            set 
            {
                this.sentTimestamp = value;
                onPropertyChanged("SentTimestamp");
            }
        }

        /// <summary>
        /// Shows the response status
        /// </summary>
        [JsonProperty("status")]
        public string Status 
        { 
            get 
            {
                return this.status; 
            } 
            set 
            {
                this.status = value;
                onPropertyChanged("Status");
            }
        }
    }
} 