/*
 * AazarKhanTelstraSMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AazarKhanTelstraSMSAPI.PCL;
using AazarKhanTelstraSMSAPI.PCL.Utilities;


namespace AazarKhanTelstraSMSAPI.PCL.Models
{
    public class GetMessageResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string mfrom;
        private string acknowledgedTimestamp;
        private string content;

        /// <summary>
        /// Where the SMS is coming from
        /// </summary>
        [JsonProperty("from")]
        public string From 
        { 
            get 
            {
                return this.mfrom; 
            } 
            set 
            {
                this.mfrom = value;
                onPropertyChanged("From");
            }
        }

        /// <summary>
        /// When the SMS was received
        /// </summary>
        [JsonProperty("acknowledgedTimestamp")]
        public string AcknowledgedTimestamp 
        { 
            get 
            {
                return this.acknowledgedTimestamp; 
            } 
            set 
            {
                this.acknowledgedTimestamp = value;
                onPropertyChanged("AcknowledgedTimestamp");
            }
        }

        /// <summary>
        /// The body or content of SMS
        /// </summary>
        [JsonProperty("content")]
        public string Content 
        { 
            get 
            {
                return this.content; 
            } 
            set 
            {
                this.content = value;
                onPropertyChanged("Content");
            }
        }
    }
} 