/*
 * AazarKhanTelstraSMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AazarKhanTelstraSMSAPI.PCL;
using AazarKhanTelstraSMSAPI.PCL.Utilities;


namespace AazarKhanTelstraSMSAPI.PCL.Models
{
    public class SendSMSToBodyObject : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string to;
        private string body;

        /// <summary>
        /// Where the SMS is being sent
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// Content of the SMS
        /// </summary>
        [JsonProperty("body")]
        public string Body 
        { 
            get 
            {
                return this.body; 
            } 
            set 
            {
                this.body = value;
                onPropertyChanged("Body");
            }
        }
    }
} 