/*
 * AazarKhanTelstraSMSAPI.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AazarKhanTelstraSMSAPI.PCL;
using AazarKhanTelstraSMSAPI.PCL.Utilities;


namespace AazarKhanTelstraSMSAPI.PCL.Models
{
    public class SendSMSResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string messageId;

        /// <summary>
        /// The message id received when SMS is sent
        /// </summary>
        [JsonProperty("messageId")]
        public string MessageId 
        { 
            get 
            {
                return this.messageId; 
            } 
            set 
            {
                this.messageId = value;
                onPropertyChanged("MessageId");
            }
        }
    }
} 